### ISSUE TITLE
HTTPS mixed-content in www.gluster.org

### ISSUE THREAD

**Issue by gtirloni** [gluster/glusterdocs#311] opened 2017-12-18 16:28 UTC
The Gluster website doesn't get labeled "secure" because a single image is being loaded through HTTP:

`http://gluster.wpengine.com/wp-content/themes/glusterTheme/Resources/Sprites/main.png`

**Comment by sankarshanmukhopadhyay** [comment] 2018-08-08 02:30
@amye @mscherer - comments and next steps please? Who can fix this? Does it need a RHBZ?

**Comment by amye** [comment] 2018-08-08 11:42
I can't reproduce this issue. 
Marking as closed. 
If still an issue, can be reopened in glusterweb.

**Closed by amye** 2018-08-08 11:42 UTC
