### ISSUE TITLE
Debian Stretch repos empty for GlusterFS 6.6

### ISSUE THREAD

**Issue by kalylian** [gluster/glusterdocs#539] opened 2020-02-10 15:53 UTC
Hi,

The GlusterFS repo for Debian 9,10 and 11 for GlusterFS 6.6 is empty ([https://download.gluster.org/pub/gluster/glusterfs/6/6.6/Debian/stretch/amd64/apt/](https://download.gluster.org/pub/gluster/glusterfs/6/6.6/Debian/stretch/amd64/apt/)). Both 6.5 and 6.7 are still available.

Is that intended?

Kind regards,

Gudrun

**Comment by sankarshanmukhopadhyay** [comment] 2020-02-11 12:51
@harigowtham - would you be aware as to why the repos would be empty?

**Comment by harigowtham** [comment] 2020-02-11 13:33
Hi,

We do have the packages for Gluster 6.6 debian available in download.gluster.org. We have it in the names stretch, buster and bullseye but missed to create the same once again under the corresponding numbers (9 is stretch, 10 is buster and 11 corresponds to bullseye.). Thought both are the same and would be fine. @Shwetha-Acharya is looking into creating a copy of the same with the corresponding numbers. It should be updated in a few minutes.

Regards,
Hari.

**Comment by Shwetha-Acharya** [comment] 2020-02-11 13:38
Hi,
I have copied stretch, buster and bullseye to corresponding versions. Can we close this bug?

Regards,
Shwetha

**Comment by sankarshanmukhopadhyay** [comment] 2020-02-11 13:45
> I have copied stretch, buster and bullseye to corresponding versions. Can we close this bug?

We'll wait for the reporter to confirm that it now works as intended and we can close it after. @Shwetha-Acharya thank you for quickly addressing the issue!

**Comment by kalylian** [comment] 2020-02-11 15:43
Works like a charm. Thanks for the quick fix!

**Closed** 2020-02-11 15:51 UTC
Labels: question
